---
- name: Cisco show version example
  hosts: Cisco
  gather_facts: false
  tasks:
    - name: run show version command on the routers
      ios_command:
        commands: show version | in Version
      register: output
    - name: print output
      debug:
        var: output.stdout_lines
